[build]
  command = "pnpm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[install]
  command = "pnpm install"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
